dist: trusty
# These builds run without the underlying libsodium dependency. This ensures the tests pass with and without it.
jdk:
  # openjdk-8 and Travis don't seem to mix, so we'll test using oraclejdk8 here.
  - oraclejdk8
  - openjdk-9
  - openjdk-10
  - openjdk-11

# This job runs the tests with the underlying dependency libsodium installed.
matrix:
  include:
    - jdk: openjdk-11
      # Libsodium is only available on the xenial build image with Travis, hence it's use here.
      dist: xenial
      addons:
        apt:
          packages:
            - libsodium-dev

before_install:
- unset _JAVA_OPTIONS

install:
- echo "Installing deps"
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- mvn test